// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdsYphUYqimru9XdYILxBoMe6rNFCrZZw',
    appId: '1:637513687020:web:1fc659611d21a7ddffeac9',
    messagingSenderId: '637513687020',
    projectId: 'truckiq-44c56',
    authDomain: 'truckiq-44c56.firebaseapp.com',
    databaseURL: 'https://truckiq-44c56-default-rtdb.firebaseio.com',
    storageBucket: 'truckiq-44c56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYECY_11FJk9zO_UB537nQXjkdVEp6xA',
    appId: '1:637513687020:android:b791ca1e82491748ffeac9',
    messagingSenderId: '637513687020',
    projectId: 'truckiq-44c56',
    databaseURL: 'https://truckiq-44c56-default-rtdb.firebaseio.com',
    storageBucket: 'truckiq-44c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuya-lcRIw6wjVVxrfJNXjBxAQ4JsqAg',
    appId: '1:637513687020:ios:1c1847095bf48a38ffeac9',
    messagingSenderId: '637513687020',
    projectId: 'truckiq-44c56',
    databaseURL: 'https://truckiq-44c56-default-rtdb.firebaseio.com',
    storageBucket: 'truckiq-44c56.firebasestorage.app',
    iosBundleId: 'com.example.truckiqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuya-lcRIw6wjVVxrfJNXjBxAQ4JsqAg',
    appId: '1:637513687020:ios:1c1847095bf48a38ffeac9',
    messagingSenderId: '637513687020',
    projectId: 'truckiq-44c56',
    databaseURL: 'https://truckiq-44c56-default-rtdb.firebaseio.com',
    storageBucket: 'truckiq-44c56.firebasestorage.app',
    iosBundleId: 'com.example.truckiqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdsYphUYqimru9XdYILxBoMe6rNFCrZZw',
    appId: '1:637513687020:web:28ff9cfed2d349a1ffeac9',
    messagingSenderId: '637513687020',
    projectId: 'truckiq-44c56',
    authDomain: 'truckiq-44c56.firebaseapp.com',
    databaseURL: 'https://truckiq-44c56-default-rtdb.firebaseio.com',
    storageBucket: 'truckiq-44c56.firebasestorage.app',
  );

}